### ISSUE TITLE
Mobs killed by Frostbite does not drop proper loot/XP

### ISSUE THREAD

**Issue by Dekamir** [MoriyaShiine/enchancement#101] opened 2023-05-15 23:39 UTC
### Mod version

1.19-14

### A description of the issue

Mobs killed by Frostbite seem to not be counted as "Killed by Player", causing loot and XP to not spawn.
It is mainly an XP issue (as I am not certain on loot drops).

This is easily recreateable by killing bunch of Chickens in a close space.

Sometimes, mobs frozen have a chance to not drop loot as well.

**Comment by MoriyaShiine** [comment] 2023-05-16 17:21
![image](https://github.com/MoriyaShiine/enchancement/assets/45156123/cacbbfcb-f293-4d0c-bd05-c15032388c3a)

I'm unable to reproduce this, can you check this in an instance with just Enchancement (on the latest available version, 1.19-18 as of now)

**Comment by Dekamir** [comment] 2023-05-16 17:37
It happens rarely, and happens especially with hostile mobs (such as Witches).
I have tested all my issues in a clean environment.
I cannot test it on 1.19-18 as latest available Enchancement for 1.19.2 is 1.19-14.

**Comment by MoriyaShiine** [comment] 2023-05-16 17:41
I just killed a bunch of Witches and they still dropped everything. If it's when Witches kill *another* mob, then it is to be expected that they won't drop player loot.

Since I am unable to reproduce either issue, I'm gonna close this for now. Please test any future issues in 1.19.4 / 1.19-18, or whatever is the most updated; I don't update old versions so issues may or may not already be fixed

**Closed by MoriyaShiine** 2023-05-16 17:41 UTC
