### ISSUE TITLE
Root tag must be a named compound tag

### ISSUE THREAD

**Issue by ItsPerona** [MoriyaShiine/enchancement#158] opened 2024-02-09 20:47 UTC
### Mod version (NOT Minecraft version)

16

### A description of the issue

When I try to join a server, server kicks me with reason "java.io.IOException: Root tag must be a named compound tag". On singleplayer works fine.

### Log or crash report

https://gist.github.com/ItsPerona/0fb18e206f131be4d777244fb3af51f5

**Comment by MoriyaShiine** [comment] 2024-02-09 20:54
Has the server updated?

**Comment by ItsPerona** [comment] 2024-02-09 20:59
> Has the server updated?

What do you mean?

**Comment by MoriyaShiine** [comment] 2024-02-09 21:02
Are the server and client on the same version?

**Comment by ItsPerona** [comment] 2024-02-09 21:02
Yes

**Comment by MoriyaShiine** [comment] 2024-02-09 21:05
Does the server have any enchanting material overrides? It might have an invalid file

**Comment by ItsPerona** [comment] 2024-02-09 21:06
I don't think so, however I can pass the entire log of the server and the client if you want

**Comment by MoriyaShiine** [comment] 2024-02-09 21:08
Please do

**Comment by ItsPerona** [comment] 2024-02-09 21:10
[Client latest.log](https://github.com/MoriyaShiine/enchancement/files/14226339/latest.log)
[Server latest.log](https://github.com/MoriyaShiine/enchancement/files/14226353/latest.log)

**Comment by MoriyaShiine** [comment] 2024-02-09 21:14
Can you try loading without Chunk Loaders?

**Comment by ItsPerona** [comment] 2024-02-09 21:15
I try, it won't take long

**Comment by ItsPerona** [comment] 2024-02-09 21:20
Now the error changes, I attach the client log because the server does not show anything.
Error: `Encountered exception while handling in channel with name "enchancement:sync_enchanting_material_map"
net.minecraft.class_148: Loading NBT data`

[latest.log](https://github.com/MoriyaShiine/enchancement/files/14226420/latest.log)

**Comment by MoriyaShiine** [comment] 2024-02-09 21:23
That's really strange, I'm not able to reproduce it. Unfortunately I think it's a mod conflict and you'll have to remove mods until you figure out which one causes it

**Comment by ItsPerona** [comment] 2024-02-09 21:26
I'm going to test then, what kind of mods can affect Enchancement?

**Comment by MoriyaShiine** [comment] 2024-02-09 21:27
No idea, but binary search is useful (removing half of your mods at a time until it works)

**Comment by ItsPerona** [comment] 2024-02-09 22:31
I'm testing, when I have it notified I'll let you know

**Comment by ItsPerona** [comment] 2024-02-09 23:42
I spent a long time trying to find the culprit for this. Since I didn't find anything clear, I deleted the Library, Config, World and UserData folder and reopened the server. Now the error does not appear

**Comment by MoriyaShiine** [comment] 2024-02-12 16:53
Must've just been a one time thing then. I'll close this since it's unable to be reproduced

**Closed by MoriyaShiine** 2024-02-12 16:53 UTC
